name: hready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  shared_preferences: ^2.5.3
  lottie: ^3.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  json_serializable: ^6.9.0
  flutter_lints: ^6.0.0
  build_runner: ^2.5.0
  hive_generator: ^2.0.1
  async: ^2.13.0
  mocktail: ^1.0.4
  intl: ^0.20.2
  file_picker: ^10.2.0
  shake: ^3.0.0
  shimmer: ^3.0.0
  jwt_decoder: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/primary.png"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.webp
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf